/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as CasesCaseIdIndexRouteImport } from './routes/cases.$caseId.index'
import { Route as CasesCaseIdAgentsRouteImport } from './routes/cases.$caseId.agents'
import { Route as CasesCaseIdDocumentsRouteImport } from './routes/cases.$caseId.documents'
import { Route as CasesCaseIdPolicyRouteImport } from './routes/cases.$caseId.policy'
import { Route as CasesCaseIdSpreadingRouteImport } from './routes/cases.$caseId.spreading'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdIndexRoute = CasesCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdAgentsRoute = CasesCaseIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdDocumentsRoute = CasesCaseIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdPolicyRoute = CasesCaseIdPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdSpreadingRoute = CasesCaseIdSpreadingRouteImport.update({
  id: '/spreading',
  path: '/spreading',
  getParentRoute: () => CasesCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/': typeof CasesIndexRoute
  '/cases/$caseId/agents': typeof CasesCaseIdAgentsRoute
  '/cases/$caseId/documents': typeof CasesCaseIdDocumentsRoute
  '/cases/$caseId/policy': typeof CasesCaseIdPolicyRoute
  '/cases/$caseId/spreading': typeof CasesCaseIdSpreadingRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesIndexRoute
  '/cases/$caseId/agents': typeof CasesCaseIdAgentsRoute
  '/cases/$caseId/documents': typeof CasesCaseIdDocumentsRoute
  '/cases/$caseId/policy': typeof CasesCaseIdPolicyRoute
  '/cases/$caseId/spreading': typeof CasesCaseIdSpreadingRoute
  '/cases/$caseId': typeof CasesCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/': typeof CasesIndexRoute
  '/cases/$caseId/agents': typeof CasesCaseIdAgentsRoute
  '/cases/$caseId/documents': typeof CasesCaseIdDocumentsRoute
  '/cases/$caseId/policy': typeof CasesCaseIdPolicyRoute
  '/cases/$caseId/spreading': typeof CasesCaseIdSpreadingRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases/$caseId'
    | '/cases/'
    | '/cases/$caseId/agents'
    | '/cases/$caseId/documents'
    | '/cases/$caseId/policy'
    | '/cases/$caseId/spreading'
    | '/cases/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/cases/$caseId/agents'
    | '/cases/$caseId/documents'
    | '/cases/$caseId/policy'
    | '/cases/$caseId/spreading'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/cases/$caseId'
    | '/cases/'
    | '/cases/$caseId/agents'
    | '/cases/$caseId/documents'
    | '/cases/$caseId/policy'
    | '/cases/$caseId/spreading'
    | '/cases/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesCaseIdRoute: typeof CasesCaseIdRouteWithChildren
  CasesIndexRoute: typeof CasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/': {
      id: '/cases/$caseId/'
      path: '/'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof CasesCaseIdIndexRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/agents': {
      id: '/cases/$caseId/agents'
      path: '/agents'
      fullPath: '/cases/$caseId/agents'
      preLoaderRoute: typeof CasesCaseIdAgentsRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/documents': {
      id: '/cases/$caseId/documents'
      path: '/documents'
      fullPath: '/cases/$caseId/documents'
      preLoaderRoute: typeof CasesCaseIdDocumentsRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/policy': {
      id: '/cases/$caseId/policy'
      path: '/policy'
      fullPath: '/cases/$caseId/policy'
      preLoaderRoute: typeof CasesCaseIdPolicyRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/spreading': {
      id: '/cases/$caseId/spreading'
      path: '/spreading'
      fullPath: '/cases/$caseId/spreading'
      preLoaderRoute: typeof CasesCaseIdSpreadingRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
  }
}

interface CasesCaseIdRouteChildren {
  CasesCaseIdAgentsRoute: typeof CasesCaseIdAgentsRoute
  CasesCaseIdDocumentsRoute: typeof CasesCaseIdDocumentsRoute
  CasesCaseIdPolicyRoute: typeof CasesCaseIdPolicyRoute
  CasesCaseIdSpreadingRoute: typeof CasesCaseIdSpreadingRoute
  CasesCaseIdIndexRoute: typeof CasesCaseIdIndexRoute
}

const CasesCaseIdRouteChildren: CasesCaseIdRouteChildren = {
  CasesCaseIdAgentsRoute: CasesCaseIdAgentsRoute,
  CasesCaseIdDocumentsRoute: CasesCaseIdDocumentsRoute,
  CasesCaseIdPolicyRoute: CasesCaseIdPolicyRoute,
  CasesCaseIdSpreadingRoute: CasesCaseIdSpreadingRoute,
  CasesCaseIdIndexRoute: CasesCaseIdIndexRoute,
}

const CasesCaseIdRouteWithChildren = CasesCaseIdRoute._addFileChildren(
  CasesCaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesCaseIdRoute: CasesCaseIdRouteWithChildren,
  CasesIndexRoute: CasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
